### ISSUE TITLE
Test SCSS

### ISSUE THREAD

**Issue by nastiatikk** [mobify/stencil#134]
This comment was in `_test.scss` file. Move it to the issue to rememberrr!

#### TODO: 
- Remove margins from component; sibling spacing can likely stay, but should be configurable.
- Test theme should be a separate import.

**Comment by ry5n** [comment]
Thanks for bringing this out; these were more notes-to-self than anything else. I’ve been working on a new Stencil 2.0 version of the Test component to support the Select component. I just double-checked the new implementation and I don’t think either of these is an issue anymore.
